### PR TITLE
BUG - Change render locations of HubCare elements on GitHub

### PR DESCRIPTION
**Pull request by Brian2397**
## Description

A function was created using PJAX, so you can reload the Github page each time you click a button.
In this function using PJAX, Init () is loaded into it.
In the init (), the Badges and the 'Hubcare' button are inserted.
Clicking on the 'Hubcare' button deletes the content of the page.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by cjjcastro** [comment]
To test it is necessary to install new libraries.  I suggest running:
```
docker-compose build
```

**Comment by filipetoyoshima** [comment]
After running `docker-compose build` and `docker-compose up`, I got this:

```
hubcare-plugin   | ERROR in ./scripts/contentscript.js
hubcare-plugin   | Module not found: Error: Can't resolve 'jquery' in '/usr/src/app/app/scripts'
hubcare-plugin   |  @ ./scripts/contentscript.js 1:0-28 140:0-1
```

**Comment by cjjcastro** [comment]
Run:
```
docker-compose exec hubcareplugin npm install
```
Or
```
docker-compose exec hubcareplugin npm install jquery
```

**Comment by cjjcastro** [comment]
docker must have used cache to mount the container

**Comment by filipetoyoshima** [comment]
Done and working!

> Run:
> 
> ```
> docker-compose exec hubcareplugin npm install
> ```
> 
> Or
> 
> ```
> docker-compose exec hubcareplugin npm install jquery
> ```

**Comment by cjjcastro** [comment]
Sorry did not understand.  What type of conflict is occurring?

**Comment by filipetoyoshima** [comment]
Ops, sorry. My bad. ZenHub isn't having any trouble with Hubcare.

The PR seems ok.

**Comment by cjjcastro** [comment]
I understood, as zenhub is a plugin that modifies github as well as hubcare I recommended to the development team to disable zenhub so as not to run the risk of modifying something modified by another plugin

**Pull request merged**
